import type { PlatformId, PlatformPreset } from "@about-fit/domain";

export const PLATFORM_PRESETS: Record<PlatformId, PlatformPreset> = {
  "taobao-main": {
    id: "taobao-main",
    label: "Taobao Main Image",
    size: [800, 800],
    format: "jpg",
    background: "white",
    aspectRatio: "1:1",
  },
  "taobao-detail": {
    id: "taobao-detail",
    label: "Taobao Detail Image",
    size: [790, 2000],
    format: "jpg",
    background: "white",
  },
  "douyin-feed": {
    id: "douyin-feed",
    label: "Douyin Feed Video",
    size: [1080, 1920],
    format: "mp4",
    background: "white",
    aspectRatio: "9:16",
    duration: [9, 15],
    fps: 30,
  },
  "douyin-cover": {
    id: "douyin-cover",
    label: "Douyin Cover Image",
    size: [1080, 1920],
    format: "jpg",
    background: "white",
    aspectRatio: "9:16",
  },
  "shopify-hero": {
    id: "shopify-hero",
    label: "Shopify Hero Image",
    size: [2048, 2048],
    format: "webp",
    background: "transparent",
    aspectRatio: "1:1",
  },
  "tiktok-shop": {
    id: "tiktok-shop",
    label: "TikTok Shop Image",
    size: [1080, 1080],
    format: "jpg",
    background: "white",
    aspectRatio: "1:1",
  },
  "amazon-a-plus-banner": {
    id: "amazon-a-plus-banner",
    label: "Amazon A+ Banner",
    size: [970, 600],
    format: "jpg",
    background: "white",
  },
  "amazon-a-plus-square": {
    id: "amazon-a-plus-square",
    label: "Amazon A+ Square",
    size: [600, 600],
    format: "jpg",
    background: "white",
    aspectRatio: "1:1",
  },
  "xiaohongshu": {
    id: "xiaohongshu",
    label: "Xiaohongshu Image",
    size: [1080, 1440],
    format: "jpg",
    background: "white",
    aspectRatio: "3:4",
  },
  "instagram-feed": {
    id: "instagram-feed",
    label: "Instagram Feed Image",
    size: [1080, 1080],
    format: "jpg",
    background: "white",
    aspectRatio: "1:1",
  },
  "instagram-story": {
    id: "instagram-story",
    label: "Instagram Story Image",
    size: [1080, 1920],
    format: "jpg",
    background: "white",
    aspectRatio: "9:16",
  },
};
